### ISSUE TITLE
运行失败后报错in `read': No such file or directory

### ISSUE THREAD

**Issue by qitaos** [vigossjjj/CrashMonkey4IOS#10]
报错信息为：

```
/Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:327:in `read': No such file or directory - /Users/buildserver/Desktop/ios-monkey/smart_monkey_result/report_20150612114103/orientation (Errno::ENOENT)
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:327:in `rotate_imgs'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:132:in `finish_running'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:50:in `block in run'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:46:in `times'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:46:in `run'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/bin/smart_monkey:51:in `<top (required)>'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/smart_monkey:23:in `load'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/smart_monkey:23:in `<main>'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

机器是iMac，系统osx 10.9.5
使用rvm重新安装了ruby2.0.0-p643
执行的真机是7.1.1系统

完整的运行脚本过程：

```
buildserver:ios-monkey buildserver$ smart_monkey -a com.pajk.personaldoctor -w ae46855fdca94d750fe40c2fcd45cfc3ad9ff111 -t 144000
INSTRUMENTS_TRACE_PATH : /Users/buildserver/Desktop/ios-monkey/*.trace
RESULT_BASE_PATH : /Users/buildserver/Desktop/ios-monkey/smart_monkey_result
{:app_path=>"com.pajk.personaldoctor", :device=>"ae46855fdca94d750fe40c2fcd45cfc3ad9ff111", :time_limit_sec=>144000, :run_count=>1, :detail_event_count=>50}
2015-06-12 11:41:05.558 instruments[45769:4b13] WebKit Threading Violation - initial use of WebKit from a secondary thread.
=================================== Start Test (1/1) =======================================
2015-06-12 11:41:06.120 instruments[45778:2307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2015-06-12 11:41:06.847 instruments[45788:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2015-06-12 11:41:08.606 instruments[45799:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Attempting iOS device system log capture via deviceconsole.
BundleID was found: com.pajk.personaldoctor
Run: ["instruments", "-w", "ae46855fdca94d750fe40c2fcd45cfc3ad9ff111", "-l", "144000000", "-t", "/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate", "com.pajk.personaldoctor", "-e", "UIASCRIPT", "/Users/buildserver/Desktop/ios-monkey/smart_monkey_result/report_20150612114103/custom.js", "-e", "UIARESULTSPATH", "/Users/buildserver/Desktop/ios-monkey/smart_monkey_result/report_20150612114103"]
2015-06-12 11:41:09.733 instruments[45808:4f03] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Instruments Usage Error : Specified target process is invalid: com.pajk.personaldoctor
instruments, version 6.1 (56160)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
Stop iOS system log capture.
2015-06-12 11:41:13.581 instruments[45819:30b] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Find new crash report: /Users/buildserver/Desktop/ios-monkey/smart_monkey_result/report_20150612114103/Run 1/DTMobileIS_2015-06-12-114254_iPhone.crash
/Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:327:in `read': No such file or directory - /Users/buildserver/Desktop/ios-monkey/smart_monkey_result/report_20150612114103/orientation (Errno::ENOENT)
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:327:in `rotate_imgs'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:132:in `finish_running'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:50:in `block in run'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:46:in `times'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/lib/smart_monkey/monkey_runner.rb:46:in `run'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/gems/smart_monkey-0.4.1/bin/smart_monkey:51:in `<top (required)>'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/smart_monkey:23:in `load'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/smart_monkey:23:in `<main>'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
    from /Users/buildserver/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vigossjjj** [comment]
Instruments Usage Error : Specified target process is invalid: com.pajk.personaldoctor, 这个bundle id是无效的，检查你的设备是否安装了这个app，并且输入了正确的bundle id，你可以通过smart_monkey --list-app查看已安装的程序。

**Comment by qitaos** [comment]
但是主要的错误是后面的ruby的错误吧，我在0.3.0上也这样错误了，但是最后能正常的生成html的报告。

**Comment by vigossjjj** [comment]
@qitaos 已经很明显了错误是你的bundle id没有输入正确，如果你使用过原生的instrument你应该知道Automation Result.plist是不会生成的，道理和这个一样，后边ruby的错误是由于你前面的错误导致的，后续这块我会加一些异常信息，帮助理解吧，希望以后出问题，自己多分析多看日志，将问题提到根上，也是对你自己能力的体现。

**Comment by qitaos** [comment]
谢谢，确实是bundleid错误了。之前光顾着看ruby错误了，没注意到前面的错误。
