### ISSUE TITLE
环境都装好了，但是执行不起来，具体报错如下

### ISSUE THREAD

**Issue by langui129** [vigossjjj/CrashMonkey4IOS#30]
没有提示bundle id错误，所以没搞懂，求助～～～
chendongdong-2:~ chendongdong$ smart_monkey -a com.baitian.wenta -s [60A3866E-0B1B-4DAB-B274-E15DF47C9E5D]
INSTRUMENTS_TRACE_PATH : /Users/chendongdong/*.trace
RESULT_BASE_PATH : /Users/chendongdong/smart_monkey_result
{:app_path=>"com.baitian.wenta", :dsym_file_path=>"/Users/chendongdong/[60A3866E-0B1B-4DAB-B274-E15DF47C9E5D]", :run_count=>1, :time_limit_sec=>nil, :detail_event_count=>50}
=================================== Start Test (1/1) =======================================
Attempting iOS Simulator system log capture via tail system.log.
Stop iOS system log capture.
/Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/lib/smart_monkey/monkey_runner.rb:202:in `device': undefined method`strip' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/lib/smart_monkey/monkey_runner.rb:87:in `block in run_a_case'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/lib/smart_monkey/monkey_runner.rb:600:in`watch_syslog'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/lib/smart_monkey/monkey_runner.rb:82:in `run_a_case'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/lib/smart_monkey/monkey_runner.rb:49:in`block in run'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/lib/smart_monkey/monkey_runner.rb:46:in `times'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/lib/smart_monkey/monkey_runner.rb:46:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.4.2/bin/smart_monkey:58:in `<top (required)>'
    from /usr/bin/smart_monkey:23:in`load'
    from /usr/bin/smart_monkey:23:in `<main>'

虚拟机安装的app

chendongdong-2:~ chendongdong$ smart_monkey --list-app
============For iPhone Simulator:
Wenta.app

**Comment by langui129** [comment]
应该是命令格式错了，设备被我改成了-w "iPhone 6 (8.4 Simulator)"就可以正常执行了
